### PR TITLE
fix: ui uses relative base paths.

### LINKED ISSUE #317: Frontend pathing is broken
Frontend uses absolute paths for routing as well as for making calls to the backend API. This means that when the app is served behind a reverse proxy both the URLs used for routing and all calls to the backend do not work.

Bonus: Some api calls use an env var with an invalid  path (https://github.com/canonical/identity-platform-admin-ui/blob/main/ui/src/api/client.tsx#L10) and some use a correct path that is hardcoded (https://github.com/canonical/identity-platform-admin-ui/blob/main/ui/src/api/identities.tsx#L9). It looks like that same is true for the rebac components (https://github.com/canonical/rebac-admin/blob/main/src/api/authentication/authentication.ts#L43)

### PR DESCRIPTION
**Pull request by edlerd**
# Done
- fix to use relative base paths
  - in case /ui/ is found in the current page url, all links and api routes rely on the prefix of the current path before and including /ui/ as base url. If /ui/ is not found, fall back to / as the base path.
- streamline api base path definitions

Fixes #317
Fixes IAM-911
Fixes WD-12306

### CODE REVIEW

File: ui/src/App.tsx [hunk 1]
```diff
@@ -33,24 +34,24 @@ const App: FC = () => {
         <Suspense fallback={<Loader />}>
           <Routes>
             <Route
-              path="/"
+              path={basePath}
```
Comment (huwshimi) [inline ui/src/App.tsx:37]: Instead of manipulating the routes, links and navigate calls you can set `basename` on the `<Router>` in index.tsx which will automatically make all other URLs relative to the base (see the last paragraph on this page: https://reactrouter.com/en/main/router-components/router).

File: ui/src/util/basePaths.ts
Comment (huwshimi) [inline ui/src/util/basePaths.ts:1]: It looks like this file could do with some tests.

**Review by huwshimi — COMMENTED** [review]
A couple of initial notes. I haven't done a QA yet.

**Review by BarcoMasile — DISMISSED** [review]
I agree with Huw's comments.
I would be ok merging this since it fixes the linked issue, but at the same time I'd explore the use of `basename` prop directly on the Router object

File: ui/src/App.tsx (hunk 1 above)
Comment (edlerd) [reply ui/src/App.tsx]: Good idea, using the react router base path now.

File: ui/src/util/basePaths.ts
Comment (edlerd) [reply ui/src/util/basePaths.ts:1]: Added test cases.

**Comment by edlerd** [comment]
Adjusted to use the router property directly to keep this clean. Also added some test cases for the path calculation.

**Review by BarcoMasile — APPROVED** [review]

**Review by huwshimi — APPROVED** [review]
Thanks for the tests and the router basename improvement, that seems much cleaner.

One improvement in the future could be to create a central API URL map that prepends the basename when initialised.
